# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SDP', '0002_auto_20161026_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='course',
        ),
        migrations.AddField(
            model_name='component',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SDP.Module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='title',
            field=models.CharField(default=1, max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SDP.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(default=1, max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SDP.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SDP.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SDP.Module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SDP.Course'),
            preserve_default=False,
        ),
    ]
