# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDP', '0004_auto_20161026_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='SDP/uploads'),
        ),
        migrations.AlterField(
            model_name='component',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='SDP/uploads'),
        ),
    ]
