# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDP', '0005_auto_20161026_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='component',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
