# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDP', '0011_auto_20161109_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Mergers and Acquisitions', 'Mergers and Acquisitions'), ('Markets', 'Markets'), ('Risk Management', 'Risk Management'), ('Securities', 'Securities'), ('Financial Modelling', 'Financial Modelling'), ('Operations', 'Operations'), ('Information Technology', 'Information Technology')], default='Mergers and Acquisitions', max_length=127),
        ),
    ]
