# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SDP', '0013_auto_20161109_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDP.Employee')),
            ],
            options={
                'permissions': (('control_access', 'Control access to the SDP through user authentication based on the user’s AB Credit username.'), ('manage_categories', 'Manage categories, including adding new categories.'), ('designate', 'Designate a user as instructor.')),
            },
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDP.Employee')),
            ],
            options={
                'permissions': (('courses_completed', 'View a list of courses completed by a specific user, together with date of completion of the course.'),),
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDP.Employee')),
            ],
            options={
                'permissions': (('modify_course', 'sole permission to modify courses they have created'),),
            },
        ),
        migrations.RemoveField(
            model_name='role',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
