# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SDP', '0014_auto_20161115_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrators',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='employee',
        ),
    ]
