# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDP', '0015_auto_20161115_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='title',
            field=models.TextField(default='NewModule', max_length=127),
            preserve_default=False,
        ),
    ]
