# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDP', '0016_module_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
