# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SDP', '0017_component_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrators',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SDP.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hr',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SDP.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SDP.Employee'),
            preserve_default=False,
        ),
    ]
