# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDP', '0018_auto_20161116_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(choices=[('File', 'File'), ('Image', 'Image'), ('Text', 'Text'), ('Quiz', 'Quiz')], default='text', max_length=127),
        ),
    ]
