# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDP', '0019_auto_20161116_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(choices=[('file', 'file'), ('image', 'image'), ('text', 'text'), ('quiz', 'quiz')], default='text', max_length=127),
        ),
    ]
