# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SDP', '0020_auto_20161116_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrators',
            options={'permissions': (('admin', 'Administrator permissions'),)},
        ),
        migrations.AlterModelOptions(
            name='hr',
            options={'permissions': (('HR', 'HR permissions'),)},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'permissions': (('instructor', 'Instructor permissions'),)},
        ),
    ]
