# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SDP', '0021_auto_20161116_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(choices=[('file', 'file'), ('image', 'image'), ('text', 'text'), ('quiz', 'quiz'), ('video', 'video')], default='text', max_length=127),
        ),
    ]
