# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDP', '0022_auto_20161126_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='answer',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='question',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
